project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('schedule.urls')),
    path('admin/', admin.site.urls),
]

#CONFIG PARA CARREGAR IMAGENS DO BANCO EM PRODUÇÃO
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

schedule/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'schedule'

urlpatterns = [
    path('create/user/', views.register, name='create_user'),
    path('schedule/<int:contact_id>/delete/', views.delete, name='delete'),
    path('schedule/<int:contact_id>/update/', views.update, name='update'),
    path('schedule/create/', views.create_contact, name='create'),
    path('contact/<int:contact_id>/details/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
]

schedule/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        
    name_category = models.CharField(max_length=20)
    
    def __str__(self) -> str:
        return f'{self.name_category}'
    
class Contact(models.Model):
    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'
        
    first_name = models.CharField(max_length=50, verbose_name='Primeiro Nome')
    last_name = models.CharField(max_length=50, verbose_name='Último Nome')
    phone_number = models.CharField(max_length=15, verbose_name='Telefone')
    email = models.EmailField(max_length=50, blank=True)
    created_date = models.DateTimeField(default=timezone.now, verbose_name='Data de Criação')
    description = models.TextField(blank=True, verbose_name='Descrição')
    show = models.BooleanField(default=True, verbose_name='Mostrar')
    picture= models.ImageField(blank=True, upload_to='pictures/%Y/%m', verbose_name='Foto')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Categoria')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Criado por:')
    
    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

schedule/forms.py
from typing import Any
from django import forms
from .models import Contact
from django.core.exceptions import ValidationError
import re
from schedule.models import Contact
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ContactForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    class Meta:
        model = Contact
        fields = ('first_name', 'last_name','phone_number','email','description', 'picture', 'category')
        
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'Escreva Aqui'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Escreva Aqui'}),
            'phone_number': forms.TextInput(attrs={'placeholder': 'Digite o número de telefone'}),
            'email': forms.TextInput(attrs={'placeholder': 'Digite o e-mail'}),
            'description': forms.Textarea(attrs={'placeholder': 'Conte mais...'})
        }
        
    
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        
        if len(first_name) < 3:
            self.add_error('first_name',ValidationError('O nome deve possuir no mínimo 3 caracteres!', code= 'invalid'))
        
        return first_name
    
    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
            
        if len(last_name) < 3:
            self.add_error('last_name',ValidationError('O nome deve possuir no mínimo 3 caracteres!', code= 'invalid'))

        return last_name
            
    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'
        
        if not re.search(regex, email):
            self.add_error('email', ValidationError('Endereço de e-mail inválido', code='invalid'))
            
        return email
    
class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        if User.objects.filter(email=email).exists():
            self.add_error('email',ValidationError('Endereço de e-mail já cadastro', code='invalid'))
        else:
            return email

schedule/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from schedule.forms import ContactForm
from schedule.models import Contact


def create_contact(request):
    form_action = reverse('schedule:create')
    
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        
        context = {
            'form': form,
            'form_action': form_action
        }
        
        if form.is_valid():
            contact = form.save()
            return redirect('schedule:update', contact_id=contact.id)
            
        return render(request, template_name='schedule/create.html', context=context)
        
    context = {
        'form': ContactForm(),
        'form_action': form_action
        }
    
    return render(request, template_name='schedule/create.html', context=context)

def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)
    form_action = reverse('schedule:update', args=(contact_id,))
    
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)
        
        context = {
            'form': form,
            'form_action': form_action
        }
        
        if form.is_valid():
            contact = form.save()
            return redirect('schedule:contact', contact_id=contact.id)
            
        return render(request, template_name='schedule/create.html', context=context)
        
    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action
        }
    
    return render(request, template_name='schedule/create.html', context=context)

def delete(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)
    
    confirmation = request.POST.get('confirmation', 'no')
    
    if confirmation == 'yes':
        contact.delete()
        return redirect('schedule:index')
    
    context = {
        'contact':contact, 
        'confirmation': confirmation
    }
    
    return render(request, template_name='schedule/contact.html', context=context)

schedule/views/contact_views.py
from django.shortcuts import render, get_list_or_404, redirect
from schedule.models import Contact
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator

def index(request):
    contacts = Contact.objects.filter(show=True).order_by('id')
    
    paginator = Paginator(contacts, 15)  # Show 15 contacts per page.

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos -',
    }
    return render(request, template_name='schedule/index.html', context=context)

def contact(request, contact_id):
    single_contact = Contact.objects.filter(pk=contact_id, show=True).first()
    
    if single_contact is None:
        raise Http404()
    
    single_title = f'{single_contact.first_name} {single_contact.last_name} - '
    
    context = {
        'contact': single_contact,
        'site_title': single_title,
    }
    return render(request, template_name='schedule/contact.html', context=context)

def search(request):

    search_value = request.GET.get('q', '').strip()
    
    if search_value == "":
        return redirect('schedule:index')
    
    
    contacts = Contact.objects.filter(show=True).filter(Q(first_name__icontains=search_value) |
                                                        Q(last_name__icontains=search_value) |
                                                        Q(email__icontains=search_value) |
                                                        Q(phone_number__icontains=search_value)).order_by('id')
    
    paginator = Paginator(contacts, 15)  # Show 15 contacts per page.

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos -',
    }
    return render(request, template_name='schedule/index.html', context=context)

schedule/views/user_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from schedule.forms import RegisterForm
from django.contrib import messages


def register(request):
    form = RegisterForm()
    
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário cadastrado com sucesso')
            
            context = {
            'form': form
            }

            return redirect('schedule:index')
        else:
            print('deu errado')
    context = {
            'form': form
        }
    
    return render(request, 'schedule/register.html', context=context)

schedule/templates/schedule/contact.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="single-contact">
    <h1 class="single-contact-name">
      {{ contact.first_name }} {{ contact.last_name }}
    </h1>

    <p><b>ID:</b> {{ contact.id }}</p>
    <p><b>E-mail:</b> {{ contact.email }}</p>
    <p><b>Phone:</b> {{ contact.phone_number }}</p>
    <p><b>Created Date:</b> {{ contact.created_date }}</p>
    <p><b>Description:</b> {{ contact.description }}</p>
    <p><b>Category:</b> {{ contact.category.name_category }}</p>

    {% if contact.picture %}
    <p><img src="contact.picture.url" alt="{{ contact.first_name }} {{ contact.last_name }}"></p>
    {% endif %}
  <div class="contact-links">
    <a class="btn btn-link" href="{% url 'schedule:update' contact.id %}">Update</a>

    <form action="{% url 'schedule:delete' contact.id %}" method="POST">
      {% csrf_token %}

      {% if confirmation == 'no' %}
        <input type="hidden" name="confirmation" value="yes">
        <button class="btn btn-link btn-delete" type="submit">Confirma?</button>
      {% else %}
        <button class="btn btn-link btn-delete" type="submit">Delete</button>
      {% endif %}
    </form>
  </div>
  </div>

{% endblock content %}

schedule/templates/schedule/create.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Contato</h2>
    
    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}

          {% if field.name == 'picture' and field.value.url %}
            <div class="form-group">
              <img src="{{ field.value.url }}" alt="">
            </div>
          {% endif %}
        {% endfor %}
      </div>

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

schedule/templates/schedule/index.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}
  <div class="responsive-table">
    <table class="contacts-table">
      <caption class="table-caption ">
        Contatos
      </caption>
      <thead>
        <tr class="table-row table-row-header">
          <th class="table-header">ID</th>
          <th class="table-header">Primeiro Nome</th>
          <th class="table-header">Último Nome</th>
          <th class="table-header">Telefone</th>
          <th class="table-header">E-mail</th>
        </tr>
      </thead>

      <tbody>
        {% for contact in page_obj %}
          <tr class="table-row">
            <td class="table-cel">
              <a class="table-link" href="{% url 'schedule:contact' contact.id %}">
                {{ contact.id }}
              </a>
            </td>
            <td class="table-cel">
              {{ contact.first_name }}
            </td>
            <td class="table-cel">
              {{ contact.last_name }}
            </td>
            <td class="table-cel">
              {{ contact.phone_number }}
            </td>
            <td class="table-cel">
              {{ contact.email }}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% else %}
<div class="single-contact">
  <h1 class="single-contact-name">
    Nenhum contato encontrado!
  </h1>
{% endif %}
{% endblock content %}

schedule/templates/schedule/register.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Criar Login</h2>
    
    <form 
      action="{{ form_action }}"
      method="POST"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}
        {% endfor %}
      </div>

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}